# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: utf8
  database: projeto_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres


production:
  adapter: postgresql
  encoding: utf8
  database: d52k6a8k0nks2p
  host: ec2-174-129-218-200.compute-1.amazonaws.com
  pool: 5
  username: zfqnpqlavmcwbf
  password: iho5lSQChNSk3PtH6nGK29UMyV
